# Generated by Django 5.0 on 2024-01-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
         old_name='Member',  
         new_name='Booksavailabel',
         
        ),
    ]
